---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
data:
  # Key value corresponds to a user name defined in Ceph cluster
  admin: QVFDZklkcGNmb2czSWhBQXVteHROTTJoUW11dDRzcTlzM2F6Vnc9PQ==
  # Key value corresponds to a user name defined in Ceph cluster
  #kubernetes: QVFCUzN0aGNYUGhOR2hBQU03Q0MydjJ4SFZQTUFicTZ4ZXpMRFE9PQ==
  # if monValueFromSecret is set to "monitors", uncomment the
  # following and set the mon there
  #monitors: BASE64-ENCODED-Comma-Delimited-Mons

